apiVersion: v1
kind: Template
metadata:
  name: redis-template
  annotations:
    description: "Description"
    iconClass: "icon-redis"
    tags: "database,nosql"
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: redis-master-deployment
    labels:
      app: redis
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: redis
    template:
      metadata:
        name: redis-master
        labels:
          app: redis
      spec:
        containers:
        - env:
          - name: REDIS_PASSWORD
            value: ${REDIS_PASSWORD}
          image: redis
          name: master
          ports:
          - containerPort: 6379
            protocol: TCP
parameters:
- description: Password used for Redis authentication
  from: '[A-Z0-9]{8}'
  generate: expression
  name: REDIS_PASSWORD
labels:
  redis: master
